ALTER TABLE Donhang
    ADD COLUMN IF NOT EXISTS TenNguoiNhan VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS DienThoaiNhan VARCHAR(20) NULL,
    ADD COLUMN IF NOT EXISTS DiaChiGiaoHang VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS MaKM INT NULL;
