<div class="page-head"><div><h1>Thanh to&#225;n</h1><div class="muted">&#272;&#417;n h&#224;ng s&#7869; hi&#7875;n th&#7883; trong trang qu&#7843;n l&#253; c&#7911;a admin.</div></div><a class="button secondary" href="store.php?url=Cart/Get_data">Quay l&#7841;i gi&#7887; h&#224;ng</a></div>
<div class="checkout-grid"><section class="panel"><h2>Th&#244;ng tin giao h&#224;ng</h2><form method="post" action="store.php?url=CustomerOrders/Place"><input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($_SESSION['shop_csrf'],ENT_QUOTES,'UTF-8'); ?>">
<label for="recipient">Ng&#432;&#7901;i nh&#7853;n</label><input id="recipient" name="recipient" required value="<?php echo htmlspecialchars($data['profile']['TenNguoiNhan'] ?: $data['profile']['TenKH'],ENT_QUOTES,'UTF-8'); ?>">
<label for="phone">S&#7889; &#273;i&#7879;n tho&#7841;i</label><input id="phone" name="phone" required value="<?php echo htmlspecialchars($data['profile']['DienThoaiNhan'] ?: $data['profile']['DienThoai'],ENT_QUOTES,'UTF-8'); ?>">
<label for="address">&#272;&#7883;a ch&#7881; nh&#7853;n h&#224;ng</label><textarea id="address" name="address" rows="3" required><?php echo htmlspecialchars($data['profile']['DiaChi'] ?? '',ENT_QUOTES,'UTF-8'); ?></textarea>
<h2>M&#227; khuy&#7871;n m&#227;i</h2><label for="promo_code">M&#227; gi&#7843;m gi&#225; (n&#7871;u c&#243;)</label><input id="promo_code" name="promo_code" maxlength="50">
<h2>Ph&#432;&#417;ng th&#7913;c thanh to&#225;n</h2><?php if (empty($data['methods'])) { ?><p>C&#7917;a h&#224;ng ch&#432;a b&#7853;t thanh to&#225;n COD.</p><?php } else { foreach($data['methods'] as $index=>$method) { ?><label class="payment-option"><input style="width:auto" type="radio" name="payment" value="<?php echo (int)$method['MaPT']; ?>" <?php echo $index===0?'required checked':''; ?>> <?php echo htmlspecialchars($method['TenPT'],ENT_QUOTES,'UTF-8'); ?></label><?php } } ?>
<button class="button" type="submit" <?php echo empty($data['methods'])?'disabled':''; ?>>&#272;&#7863;t h&#224;ng</button></form></section>
<aside class="panel"><h2>&#272;&#417;n h&#224;ng</h2><?php foreach($data['items'] as $item) { ?><div class="summary-line"><span><?php echo htmlspecialchars($item['TenSP'],ENT_QUOTES,'UTF-8'); ?> &times; <?php echo (int)$item['CartQuantity']; ?></span><strong><?php echo number_format((float)$item['LineTotal'],0,',','.'); ?> &#8363;</strong></div><?php } ?><hr><div class="summary-line summary-total"><span>T&#7893;ng c&#7897;ng</span><span><?php echo number_format((float)$data['total'],0,',','.'); ?> &#8363;</span></div></aside></div>
